apiVersion: v1
kind: ServiceAccount
metadata:
  name: athena-mcp-server
  annotations:
    # Replace with your actual IAM role ARN that has Athena permissions
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/athena-mcp-server-role"