apiVersion: v1
kind: Service
metadata:
  name: athena-mcp-server
  labels:
    app: athena-mcp-server
spec:
  ports:
  - port: 8050
    targetPort: 8050
    protocol: TCP
    name: http
  selector:
    app: athena-mcp-server
  type: ClusterIP